### ISSUE TITLE
Custom mixin or decorator to check blocked users

### ISSUE THREAD

**Issue by Programmer-yar** [turian/audio-discrimination-crowdsource#33]
Create a custom mixin or decorator to be added to pages where we want to block the user

**Comment by DeFidelity** [comment]
Is there a difference between a locked and blocked user?

If there is, it means changes need to be done right from the user model because User currently has no attribute is_blocked, but is_locked is present and mixin has been created for the user-locked feature, which has been proven to work redirection of users to thanks page by an attached unit test.

**Comment by turian** [comment]
Locked = blocked
